version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-patch", "version-update:semver-minor"]
  open-pull-requests-limit: 5
